export const SYSTEM_PERMISSIONS = [
  '*',
  'dashboard:view',
  'catalog:manage',
  'theme:manage',
  'design:view',
  'cart:view',
  'order:manage',
  'payment:view',
  'after-sale:manage',
  'review:manage',
  'bracelet:manage',
  'thought-card:manage',
  'content:manage',
  'file:upload',
  'user:manage',
  'admin:manage',
  'rbac:manage',
  'audit:view',
] as const;
